### ISSUE TITLE
Unit tests via Travis-CI to test examples

### ISSUE THREAD

**Issue by slarson** [openworm/movement_validation#107]
Testing the examples will make for an easy way to have automated regression testing for the project.

Here's a class from PyOpenWorm for testing examples that can be used as a model. https://github.com/openworm/PyOpenWorm/blob/alpha0.5/tests/test.py#L54

**Comment by MichaelCurrie** [comment]
FYI that example uses unittest and so far I have been using nose, which is a package based on unittest.  It seems popular so perhaps it's best that we keep using nose.

**Comment by MichaelCurrie** [comment]
@slarson so far running our examples requires access to several HDF5 and JSON files, which are stored in a Google Drive folder that our current build process assumes is mirrored on the user's local drive.  What's the best practice for getting the Travis CI build machine to access files?  I can see it's got documentation on instantiating a build database, but what if I just want to test something that requires opening one of those HDF5 files to initialiaze some data?  Thanks!

**Comment by MichaelCurrie** [comment]
Maybe a solution is: https://github.com/blog/1986-announcing-git-large-file-storage-lfs

**Comment by slarson** [comment]
@MichaelCurrie 
Git large file storage is interesting, but we may run into the 1GB limit rather quickly.  

Folks on the Geppetto side have been hosting large files in a public dropbox folder that they can get a publicly accessible URL to that doesn't require authentication (i.e. anonymous access).  If it is possible to do the same thing on GDrive, I'd suggest doing that (perhaps by making permissions to the file world readable).  If not, we can host it in the OpenWorm public dropbox?

**Comment by JimHokanson** [comment]
This is taken care of with 5826d5a4bfebcb20839466669fdcd440c276b6e3. Currently we need to specify which examples should be run.

I ended up downloading files directly from Google Drive.

**Comment by MichaelCurrie** [comment]
Awesome!  I see that currently only one example is actually being run, the rest you've commented out, because of all the bugs. (see exerpt from `examples/__init__.py` below)  Still, awesome that you got the examples downloading from Google Drive!

```
from .validate_features import main as validate_features

#from .normalized_worm import NormalizedWorm
#from .video_info import VideoInfo
#from .features.worm_features import WormFeatures
#from .worm_plotter import NormalizedWormPlottable
#from .basic_worm import BasicWorm
#
#from .features.feature_processing_options import FeatureProcessingOptions
#
#from .statistics.histogram_manager import HistogramManager
#from .statistics.manager import StatisticsManager
```
