### ISSUE TITLE
Misplaced PDF link

### ISSUE THREAD

**Issue by DCPhasedLogix** [openworm/movement_validation#116]
The link to the code progress pdf is broken on the guide to contributors page.

https://github.com/openworm/movement_validation/blob/master/documentation/Code%20Progress.pdf

**Comment by MichaelCurrie** [comment]
Fixed with 161f66ae6fed6bcc2b5e9509d67868da1e8b33cd.  Thanks, @DCPhasedLogix for pointing this out.
