### ISSUE TITLE
Remove Shapely dependency - make optional

### ISSUE THREAD

**Issue by JimHokanson** [openworm/movement_validation#118]
We currently only use Shapely for running the point-in-polygon algorithm for computing orientation. Since it is not a typical install and since it requires binary code, installing it is just an unnecessary step towards getting people to be able to work with the code base. 

Going forward it should be made optional by importing it only if it is present, otherwise relying on a yet to be written stand-in for that function.

**Comment by JimHokanson** [comment]
This should be handled now. Let's remove it from Travis and any import statements and we should be set.

**Comment by JimHokanson** [comment]
@MichaelCurrie I believe this is done, correct?

**Comment by MichaelCurrie** [comment]
Yes.  Specificially @ver228 's new eccentricity code made the old eccentricity code with its shapely dependency unnecessary.  So I removed it, with commit 6220a4c10e1343d9b44bcb80066e3725d1653c56.  Shapely no longer necessary, and the commit also removed it from the `.travis.yml` file as well.
