### ISSUE TITLE
Errors running pre_features.py code

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/movement_validation#122]
If I run JSON demo.py, I get the following messages.

in NormalizedWorm consructor
in BasicWorm constructor
In WormPartition initializer
in BasicWorm constructor
in NormalizedWorm consructor
in BasicWorm constructor
In WormPartition initializer
in BasicWorm constructor
Calculating pre-features

Intel MKL ERROR: Parameter 6 was incorrect on entry to DGELSD.

Intel MKL ERROR: Parameter 6 was incorrect on entry to DGELSD.

Intel MKL ERROR: Parameter 6 was incorrect on entry to DGELSD.

Intel MKL ERROR: Parameter 6 was incorrect on entry to DGELSD.

Intel MKL ERROR: Parameter 6 was incorrect on entry to DGELSD.

Intel MKL ERROR: Parameter 6 was incorrect on entry to DGELSD.

Intel MKL ERROR: Parameter 6 was incorrect on entry to DGELSD.

Intel MKL ERROR: Parameter 6 was incorrect on entry to DGELSD.
C:\Backup\WinPython-64bit-3.3.2.3\python-3.4.3.amd64\lib\site-packages\numpy\lib\polynomial.py:588: RankWarning: Polyfit may be poorly conditioned
  warnings.warn(msg, RankWarning)
C:\Backup\WinPython-64bit-3.3.2.3\python-3.4.3.amd64\lib\site-packages\numpy\lib\polynomial.py:588: RankWarning: Polyfit may be poorly conditioned
  warnings.warn(msg, RankWarning)
C:\Backup\WinPython-64bit-3.3.2.3\python-3.4.3.amd64\lib\site-packages\numpy\lib\polynomial.py:588: RankWarning: Polyfit may be poorly conditioned
  warnings.warn(msg, RankWarning)
C:\Backup\WinPython-64bit-3.3.2.3\python-3.4.3.amd64\lib\site-packages\numpy\lib\polynomial.py:588: RankWarning: Polyfit may be poorly conditioned
  warnings.warn(msg, RankWarning)
C:\Backup\WinPython-64bit-3.3.2.3\python-3.4.3.amd64\lib\site-packages\numpy\lib\polynomial.py:588: RankWarning: Polyfit may be poorly conditioned
  warnings.warn(msg, RankWarning)
C:\Backup\WinPython-64bit-3.3.2.3\python-3.4.3.amd64\lib\site-packages\numpy\lib\polynomial.py:588: RankWarning: Polyfit may be poorly conditioned
  warnings.warn(msg, RankWarning)
C:\Backup\WinPython-64bit-3.3.2.3\python-3.4.3.amd64\lib\site-packages\numpy\lib\polynomial.py:588: RankWarning: Polyfit may be poorly conditioned
  warnings.warn(msg, RankWarning)
C:\Backup\WinPython-64bit-3.3.2.3\python-3.4.3.amd64\lib\site-packages\numpy\lib\polynomial.py:588: RankWarning: Polyfit may be poorly conditioned
  warnings.warn(msg, RankWarning)
..\movement_validation\pre_features.py:403: RuntimeWarning: invalid value encountered in true_divide
  dx_across = dx_across/d_across
..\movement_validation\pre_features.py:404: RuntimeWarning: invalid value encountered in true_divide
  dy_across = dy_across/d_across
..\movement_validation\pre_features.py:156: RuntimeWarning: invalid value encountered in less
  possible = (dp[1:-2] < dp[2:-1]) & (dp[1:-2] < dp[0:-3])
..\movement_validation\pre_features.py:295: RuntimeWarning: invalid value encountered in greater
  elif np.sum((v_n1c1*v_n2c2) > 0):
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Backup\WinPython-64bit-3.3.2.3\python-3.4.3.amd64\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 680, in runfile
    execfile(filename, namespace)
  File "C:\Backup\WinPython-64bit-3.3.2.3\python-3.4.3.amd64\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 85, in execfile
    exec(compile(open(filename, 'rb').read(), filename, 'exec'), namespace)
  File "C:/Users/mcurrie/Desktop/GitHub/movement_validation/examples/JSON demo.py", line 134, in <module>
    main()
  File "C:/Users/mcurrie/Desktop/GitHub/movement_validation/examples/JSON demo.py", line 40, in main
    nw_calculated = NormalizedWorm.from_BasicWorm_factory(bw)
  File "..\movement_validation\NormalizedWorm.py", line 88, in from_BasicWorm_factory
    nw.calculate_pre_features()
  File "..\movement_validation\NormalizedWorm.py", line 261, in calculate_pre_features
    self.non_vulva_contour)
  File "..\movement_validation\pre_features.py", line 416, in computeWidths
    I_1,I_2 = WormParsing.h__updateEndsByWalking(d_across,match_I1,s1,s2,END_S1_WALK_PCT)
  File "..\movement_validation\pre_features.py", line 198, in h__updateEndsByWalking
    p1_I,p2_I = WormParsing.h__getPartnersViaWalk(0,end_s1_walk_I,0,end_s2_walk_I,d_across,s1,s2)
  File "..\movement_validation\pre_features.py", line 334, in h__getPartnersViaWalk
    p1_I[cur_p_I] = c1
IndexError: index 200 is out of bounds for axis 0 with size 200

**Comment by MichaelCurrie** [comment]
Sorry @pgleeson I accidentally tagged you on this issue.

**Comment by JimHokanson** [comment]
@MichaelCurrie It seems you have created an error in my code and now you want me to fix it :wink:

**Comment by MichaelCurrie** [comment]
OK I'll work on it :)

**Comment by MichaelCurrie** [comment]
But have you seen anything like it?  Maybe give me a hint?  ;)

**Comment by JimHokanson** [comment]
I'm not sure. The problem is that the input is wrong. You are passing in the skeleton as the contour and expecting logical results :frowning: There is perhaps some need to error check more on my end but it would be better to do with a real problem, not one that has been fabricated.

FYI, the BasicWorm definition is also problematic. The main issue is that "my" BasicWorm is not normalized, and thus does not fit into a nicely shaped array. There is also a difference in contour definition.

**Comment by MichaelCurrie** [comment]
Everything @JimHokanson mentioned in his last comment has now been addressed, and this bug no longer happens, since we are properly passing a "heterocardinal" skeleton.
