### ISSUE TITLE
Go back from .rst to .md

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/movement_validation#123]
Apparently we can get back to the more accessible .md format for our documents, and still maintain compatibility with [readthedocs](https://coderwall.com/p/vemncg/what-is-the-difference-rest-docutils-sphinx-readthedocs).  Yay!

Here are the details:
https://github.com/openworm/openworm_docs/pull/23#issuecomment-100318309

I say let's go back to .md format.

**Comment by slarson** [comment]
Yup, BTW, check [this](https://github.com/openworm/openworm_docs/tree/master/rst-to-md-conversion) for details on how to do it.  Ask @travs if you have questions!

**Comment by MichaelCurrie** [comment]
I posted a $5 USD bounty for this easy issue to see if the bounty system works.  Feel free to try to claim it!

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=14332461)](https://www.bountysource.com/issues/14332461-go-back-from-rst-to-md?utm_source=14332461&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by MichaelCurrie** [comment]
@clbarnes go to [![Bountysource](https://api.bountysource.com/badge/issue?issue_id=14332461)](https://www.bountysource.com/issues/14332461-go-back-from-rst-to-md?utm_source=14332461&utm_medium=shield&utm_campaign=ISSUE_BADGE) to claim your bounty.
