### ISSUE TITLE
Compare normalized worm instances

### ISSUE THREAD

**Issue by JimHokanson** [openworm/movement_validation#126]
The equality operator should be finished for Normalized Worm. This will allow us to know if our "pre features" calculations are roughly equivalent to the methods originally used by the Schafer lab.

See [`test_normalized_worm_creation.py`](https://github.com/openworm/movement_validation/blob/master/examples/test_normalized_worm_creation.py) in the examples folder.

This code would be best if the feature_comparison code was moved to a more general "compare data" module of some sort.

Besides using correlation for comparison, a normalized distance comparison that could catch extreme outliers would also be useful.

**Comment by MichaelCurrie** [comment]
>>This code would be best if the feature_comparison code was moved to a more general "compare data" module of some sort.

This might be a good start (in [basic_worm.py](https://github.com/openworm/movement_validation/blob/master/movement_validation/basic_worm.py)):

```Python
def nested_equal(v1, v2):
    """
    Compares two complex data structures.
    This handles the case where numpy arrays are leaf nodes.
    """
    if isinstance(v1, str) or isinstance(v2, str):
        return v1 == v2
    if isinstance(v1, np.ndarray) or isinstance(v2, np.ndarray):
        return np.array_equal(v1, v2)
    if isinstance(v1, dict) and isinstance(v2, dict):
        return nested_equal(v1.items(), v2.items())
    if isinstance(v1, Iterable) and isinstance(v2, Iterable):
        return all(nested_equal(sub1, sub2) for sub1, sub2 in zip(v1, v2))
    return v1 == v2
```

**Comment by JimHokanson** [comment]
@MichaelCurrie What is the status on this?

**Comment by MichaelCurrie** [comment]
I didn't use `nested_equal`; instead I used `utils.compare_attributes`.  Definitely done, and there are two unit tests for it, in [`test_pre_features.py`](https://github.com/openworm/movement_validation/blob/master/tests/test_pre_features.py), which replaced `test_normalized_worm_creation.py`

```
    def __eq__(self, other):
        """
        Compare this Normalized worm against another.

        # Idea from @JimHokanson:
        # TODO: Do this on a frame by frame basis, do some sort of distance 
        # computation rather than all together. This might hide bad frames        
        
        """
        attribute_list = ['skeleton_x', 'skeleton_y',
                          'ventral_contour_x', 'ventral_contour_y',
                          'dorsal_contour_x', 'dorsal_contour_y',
                          'angles', 'widths', 'length', 'area']

        return utils.compare_attributes(self, other, attribute_list,
                                        high_corr_value=0.94,
                                        merge_nans_list=['angles'])
```
