### ISSUE TITLE
Areas and Eccentricity code: speedup by rasterization

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/movement_validation#130]
The calculation of head_area, tail_area, etc, in NormalizedWorm, and later, the Posture.Eccentricity feature, can likely both be calculated more quickly if we have stored a "rasterized" version of the worm at each frame.

If we have done so, head_area can be calculated just by something like a [flood-fill](http://en.wikipedia.org/wiki/Flood_fill) operation to count pixels.

Similarly, eccentricity requires solving the point-in-polygon problem, which we are currently solving using the Shapely third-party library, introducing an expensive step for each frame, and also introducing a dependency on the Shapely library.

For these reasons it would be favourable if we could quickly rasterize and efficiently store the bitmaps in NormalizedWorm for use in Eccentricity.  I'm not sure if this would massively increase space requirements for the in-memory and serialized NormalizedWorm objects, however.

(Credit to @JimHokanson for the thinking behind this, btw)

**Comment by ver228** [comment]
Hey, I found a method that speeds up the calculation of the eccentricities dramatically. The basic idea is using the image moments (http://en.wikipedia.org/wiki/Image_moment) obtained from the contour using openCV (http://docs.opencv.org/doc/tutorials/imgproc/shapedescriptors/moments/moments.html).

I check with calculating the worm pixels using openCV drawContour, and using the code on h__calculateSingleValues to calculate the eccentricity. I obtain a very good correlation between those methods. 

![eccentricity contour moment vs full image](https://cloud.githubusercontent.com/assets/8364368/8013106/64c9b5fc-0bbe-11e5-9228-f76696f97803.png)

However, if I compared with the Shafer's lab results. Some of the contours show discrepancies. 
![eccentricity contour moment vs matlab method](https://cloud.githubusercontent.com/assets/8364368/8013114/7dd2310a-0bbe-11e5-9e39-0806eab36d0f.png)

Talking with Andre, the implemented current method uses a much corse grain grid that the one I obtain from openCV:drawContour, therefore this second method should be more accurate. By consequence the image moment method should be quite reliable.

Below is the code I used. Let me know your opinion.

```python
# -*- coding: utf-8 -*-
"""
Created on Fri Jun  5 08:11:59 2015

@author: ajaver
"""
import cv2
import numpy as np
import matplotlib.pylab as plt

import sys
import os

sys.path.append('../../movement_validation')
from movement_validation import user_config, NormalizedWorm
from movement_validation import WormFeatures

# Set up the necessary file paths for file loading
#----------------------
base_path = os.path.abspath(user_config.EXAMPLE_DATA_PATH)

matlab_generated_file_path = os.path.join(
    base_path,'example_video_feature_file.mat')

data_file_path = os.path.join(base_path,"example_video_norm_worm.mat")

# Load the normalized worm from file
nw = NormalizedWorm.from_schafer_file_factory(data_file_path)
#load and calculate data for comparison
matlab_worm_features = WormFeatures.from_disk(matlab_generated_file_path)

#Since the first and the last points of vulva and non_vulva contour are equal
contour = np.concatenate((nw.vulva_contour, nw.non_vulva_contour[-1::-1,:,:])) 

#opencv does not like float64, this actually make sense for image data where 
#we do not require a large precition in the decimal part. This could save quite a lot of space
contour = contour.astype(np.float32)
tot = contour.shape[-1]

#--------------------
#let's calculate the eccentricity from the contour moments
eccentricity = np.full(tot, np.nan);
orientation = np.full(tot, np.nan);
for ii in range(tot):
    worm_cnt = contour[:,:,ii];
    if ~np.any(np.isnan(worm_cnt)):
        moments  = cv2.moments(worm_cnt)
        
        a1 = (moments['mu20']+moments['mu02'])/2
        a2 = np.sqrt(4*moments['mu11']**2+(moments['mu20']-moments['mu02'])**2)/2
        
        minor_axis = a1-a2
        major_axis = a1+a2
        
        eccentricity[ii] = np.sqrt(1-minor_axis/major_axis)
        orientation[ii] = (180 / np.pi)*np.arctan2(2*moments['mu11'], (moments['mu20']-moments['mu02']))/2
#%%
#--------------------
#now let's calculate the eccentricity by creating a binary image with a worm image
eccentricity_s = np.full(tot, np.nan);
orientation_s = np.full(tot, np.nan);
for ii in range(tot):
    worm_cnt = contour[:,:,ii];
    
    #stop if the contour is not valid
    if np.any(np.isnan(worm_cnt)):
        continue
    
    #the minimum value of the contour will be the image upper-left corner
    corner = np.min(worm_cnt, axis=0)
    worm_cnt = worm_cnt-corner
    
    #after subracting the corner the maximum contour values will be the other corner
    im_size = np.max(worm_cnt, axis=0)[::-1] #the coordinate systems used by opencv is different from the numpy's one
    
    im_dum = np.zeros(im_size);
    
    #draw contours
    cv2.drawContours(im_dum, [worm_cnt.astype(np.int32)], 0, 1, -1);
    
    #get contour points and substract the center of mass
    y,x = np.where(im_dum)
    x = x-np.mean(x)
    y = y-np.mean(y)
    
    #same code as in h__calculateSingleValues in postures_features.py
    N = float(len(x))
    # Calculate normalized second central moments for the region.
    uxx = np.sum(x * x) / N
    uyy = np.sum(y * y) / N
    uxy = np.sum(x * y) / N
    
    # Calculate major axis length, minor axis length, and eccentricity.
    common = np.sqrt((uxx - uyy) ** 2 + 4 * (uxy ** 2))
    majorAxisLength = 2 * np.sqrt(2) * np.sqrt(uxx + uyy + common)
    minorAxisLength = 2 * np.sqrt(2) * np.sqrt(uxx + uyy - common)
    eccentricity_s[ii] = 2 * np.sqrt((majorAxisLength / 2) ** 2 - (minorAxisLength / 2) ** 2) / majorAxisLength
    
    # Calculate orientation.
    if (uyy > uxx):
        num = uyy - uxx + np.sqrt((uyy - uxx) ** 2 + 4 * uxy ** 2)
        den = 2 * uxy
    else:
        num = 2 * uxy
        den = uxx - uyy + np.sqrt((uxx - uyy) ** 2 + 4 * uxy ** 2)
    
    orientation_s[ii] = (180 / np.pi) * np.arctan(num / den) 

        
#%%
plt.figure()
plt.plot(eccentricity, eccentricity_s, '.')
plt.xlabel('Eccentricity (contour opencv moments)')
plt.ylabel('Eccentricity (filled contour)')
plt.savefig('Eccentricity contour moment vs full image.png')
#%%
import matplotlib.pylab as plt
plt.figure()
plt.plot(matlab_worm_features.posture.eccentricity, eccentricity, '.')
plt.xlabel('Eccentricity (MATLAB file)')
plt.ylabel('Eccentricity (contour opencv moments)')
plt.savefig('Eccentricity contour moment vs MATLAB method.png')
```

**Comment by MichaelCurrie** [comment]
Hey @ver228, this is fantastic!  If you don't mind we'll move discussion of this over to the other topic you opened, #134.

As for areas, which I reference in my first post on this issue, I'll just mention for posterity that areas were handled by a separate issue, #127, using the Shoelace formula and so rasterization turned out not to be necessary.
