### ISSUE TITLE
Tests are not running in  TravisCI

### ISSUE THREAD

**Issue by JimHokanson** [openworm/movement_validation#138]
I'm 99% sure based on elapsed time that the nosetests are not running in TravisCI

**Comment by MichaelCurrie** [comment]
Make that 100%.  I [just made one of the tests](d4b9eff51f4213cee0e4c9385138e5e59efbd1b9) `assert(1 == 0)` and [the build is still passing](https://travis-ci.org/openworm/movement_validation/builds/66980858).

**Comment by JimHokanson** [comment]
Ok. So I apparently had a lot of work left to do in getting OpenCV to actually work. I have a better picture of what was going wrong which I'll write up at some point. The tests are running but it can't find the files. My guess is that we need to change the file permissions since I'm pretty sure the path is correct, unless I'm making a spelling error.

I also removed the Python version support but now that I know what I'm doing (sort of) it shouldn't be too bad to add back in.

**Comment by JimHokanson** [comment]
Tests are now running. LOTS of bugs were present

**Comment by MichaelCurrie** [comment]
Hey @JimHokanson are you currently only running the build on Python 3.3?

**Comment by JimHokanson** [comment]
That is correct. I am going to write another issue that addresses that.
