### ISSUE TITLE
Rename vulva_contour to ventral_contour and non_vulva_contour to dorsal_contour

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/movement_validation#140]
Is there a reason why we couldn't do this?  Am I missing something?  Because I think my suggested names are more elegant and easy to say.

**Comment by JimHokanson** [comment]
I like it

**Comment by MichaelCurrie** [comment]
OK I made the change with commit 59a4128b38042601e18a90f5dff65ea6dec2e5da.

Trivia: *Not one pieces of code in features/ contains any reference to the worm's contour!*  All features use only the other 6 normalized worm measurements: `skeleton`, `angles`, `area`, `length`, `widths`, plus some metadata from `video_info`: `fps`, `ventral_mode` and `frame_codes`.
