### ISSUE TITLE
Clean up .travis.yml and bring back Python version testing

### ISSUE THREAD

**Issue by JimHokanson** [openworm/movement_validation#142]
The .travis.yml file is now working but it is a bit of a mess and also only tests Python 3.3. Python 2.7 and 3.4 should be added back (requires better path naming).

**Comment by MichaelCurrie** [comment]
I created a branch to work on this problem (https://github.com/openworm/movement_validation/tree/Get-Travis-On-All-Versions)

**Comment by MichaelCurrie** [comment]
Fixed by 669b81b575ee1060522951fd842504b9f39c5909

Now we're testing for Python 2.7, 3.3, 3.4, and 3.5.
