### ISSUE TITLE
From nw->bw->nw, problem with angles

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/movement_validation#145]
Running `test_normalized_worm_creation.py` on a nw->bw->nw pipeline, we have a problem with angles: `Shape mismatch after NaN filter: angles`:

```
Now let's calculate nw from bw_from_nw
{'h__getMatches': 22.17799999890849, 'hstack': 0.2530000002589077, 'h__computeNormalVectors': 0.8900000008288771, 'final calculations': 0.6290000001899898, 'h__updateEndsByWalking': 4.50600000214763, 'h__roundToOdd': 24.1409999972675, 'transpose': 0.5419999996665865, 'h__getBounds': 0.2760000005364418}
compute_skeleton_and_widths: 53.508s
angles: 1.513s
normalize_all_frames_xy(h_skeleton): 0.702s
normalize_all_frames(nw.widths, h_skeleton): 0.515s
normalize_all_frames_xy(bw.ventral_contour): 0.671s
normalize_all_frames_xy(bw.dorsal_contour): 0.718s
compute_area: 0.109s
length: 0.000s
Shape mismatch after NaN filter: angles
Corr value too low for widths: 0.996
Corr value too low for length: 0.943
Corr value too low for area: 0.977
Calculating Morphology Features
Calculating Locomotion Features
Calculating Posture Features
Calculating Path Features
locomotion.velocity: 0.218s
locomotion.motion_events: 0.016s
locomotion.crawling_bends: 8.876s
locomotion.foraging_bends: 0.172s
locomotion.turns: 0.109s
```

**Comment by MichaelCurrie** [comment]
It appears that calculated angles have exactly 400 more NaN entries across all frames than the loaded angles:
```
(Pdb) len(np.flatnonzero(np.isnan(nw.angles)))
96418
(Pdb) len(np.flatnonzero(np.isnan(nw_calculated.angles)))
96818
(Pdb) len(np.flatnonzero(~np.isnan(nw_calculated.angles)))
130640
(Pdb) len(np.flatnonzero(~np.isnan(nw.angles)))
131040
(Pdb) 
```

**Comment by MichaelCurrie** [comment]
```
a1 = np.array([np.all(np.isnan(nw.angles[:,x])) for x in range(4642)])
a2 = np.array([np.all(np.isnan(nw_calculated.angles[:,x])) for x in range(4642)])
(Pdb) np.all(a1 == a2)
True
```

**Comment by MichaelCurrie** [comment]
After dumping the data into pandas:

```
    angles1 = pd.DataFrame(nw.angles)
    angles2 = pd.DataFrame(nw_calculated.angles)
    
    angles = pd.concat([angles1, angles2])
    angles.to_csv('angles.csv')
```

And then taking the transpose and looking at the CSV zoomed out in Excel, I see that the full-NaN periods are fine, it's the first and last couple of angles that sometimes don't get calculated for some reason.

![image](https://cloud.githubusercontent.com/assets/5267078/8370283/e973843a-1b82-11e5-9449-80eadc52fe2d.png)

**Comment by MichaelCurrie** [comment]
Zooming out further, this is actually a pretty beautiful way to visualize the angles as they move in waves along the worm's body:

![image](https://cloud.githubusercontent.com/assets/5267078/8370335/99bb38c4-1b83-11e5-8a32-981c5e6e45d4.png)

**Comment by MichaelCurrie** [comment]
Looking at the skeletons (loaded / re-calculated) for one problem frame, frame 21:

![image](https://cloud.githubusercontent.com/assets/5267078/8370475/67fe60a2-1b85-11e5-8bb7-093df0da3255.png)

**Comment by MichaelCurrie** [comment]
the 49-point normalized ventral and dorsal contour, when passed into `compute_skeleton_and_widths`, results in a **47**-point skeleton, which is passed to `compute_angles`, which calculates 47 angles until the last step of `compute_angles`, which uses `normalize_all_frames` to normalize the temporary angle list to 49 points.

So it would seem that there is a bug in `compute_skeleton_and_widths` which does not act in an appropriately "idempotent" way when faced with a 49-point ventral and dorsal contour.

I confirmed this with the control case of running this against a normal 200+ point heterocardinal contour from `example_contour_and_skeleton_info.mat`.

**Comment by MichaelCurrie** [comment]
The reduction from 49 points to 47 points takes place in the following:

```
I_1, I_2 = WormParsing.h__updateEndsByWalking(d_across, match_I1, s1, s2, END_S1_WALK_PCT)

            # We're looking to the left and to the right to ensure that
            # things are ordered
            #                                    current is before next 
is_good = np.hstack((True, np.array((I_2[1:-1] <= I_2[2:]) & \
            #                    current after previous            
                                  (I_2[1:-1] >= I_2[:-2])), 
                                  True))

            I_1 = I_1[is_good]
            I_2 = I_2[is_good]
            
            s1_x  = s1[0, I_1]
            s1_y  = s1[1, I_1]
            s1_px = s2[0, I_2] #s1_pair x
            s1_py = s2[1, I_2]
...

**Comment by JimHokanson** [comment]
I'm not really sure that this is a bug. There's no reason to expect that they would be exactly the same.

**Comment by JimHokanson** [comment]
So without looking too closely at the code my guess is that things are failing because of a mismatch in size on the smoothing that is done when calculating angles. In general we might benefit from reducing the # of points used in calculating the skeleton, see issue #144 . For small entries, such as this one where we are starting with the normalized worm, and upsampling (rather than downsampling) might be necessary, and would likely remove the NaN mismatch.

To test this just upsample the skeleton after it has been processed and see if that fixes the "problem".

**Comment by MichaelCurrie** [comment]
OK I [implemented upsampling](cd1734f74d68b7d5a78ccd4117533ba40bf84797) as you suggested but unfortunately it did not change the message.  Actually upsampling also somehow causes length to have a lower correlation somehow.  My guess is that it's an off-by-one error in the code I linked in my previous comment.

**Comment by MichaelCurrie** [comment]
I tried creating a special case in h__updateEndsByWalking if the number of points is 49 or less:

```
        # Don't update ends if we are already at a very small number of 
        # points        
        if n_s1 <= config.N_POINTS_NORMALIZED:
            I_1 = np.arange(n_s1)
            I_1 = np.flatnonzero(np.ones(len(match_I1), dtype=np.bool))
            I_2 = match_I1
            # Truncate any indices not between 0 and the length of s2
            I_2[I_2 < 0] = 0
            I_2[I_2 >= n_s2] = n_s2 - 1
            return (I_1, I_2)
```

But this did not work in all frames and further lowered the correlation with the previously calculated value for skeleton length.

**Comment by MichaelCurrie** [comment]
I give up! :)

Here's my final commit on this: cdf9c9f85d2ace0b18cec58031f2caae2169ba7b

I added the flag `merge_nans=True` to the NormalizedWorm.__eq__ code so now NaNs for angles are ignored.
