### ISSUE TITLE
Create formal test harness

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/movement_validation#71]
Create a proper test harness for the movement_validation repo using [Travis CI](https://travis-ci.org/) and more feature examples from Schafer Lab (maybe 5?)

**Comment by MichaelCurrie** [comment]
This is now done and passing with commit f303f0bb0ce3a9c667d0006dc6d43f3a09240405.  Obviously many tests still need to be written, but the harness is ready and able to be used.

**Comment by slarson** [comment]
Congrats!  There's new work on the ChannelWorm project on instantiating a "hello world" test using SciUnit, thanks to the efforts of @travs @gsarma @rgerkin.  That branch is also looping in TravisCI.  Check it out here: https://github.com/VahidGh/ChannelWorm/blob/tests/tests/hello_model_test.py
