### ISSUE TITLE
Convert statistics code

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/movement_validation#76]

**Comment by MichaelCurrie** [comment]
This was completed in November 2014.

**Comment by JimHokanson** [comment]
Technically I believe the statistics have yet to be converted, just the histogram code.

The statistics code starts with:
https://github.com/JimHokanson/SegwormMatlabClasses/blob/master/%2Bseg_worm/%2Bstats/%40manager/manager.m

and the meat is in:
https://github.com/JimHokanson/SegwormMatlabClasses/blob/master/%2Bseg_worm/%2Bstats/%40manager/initObject.m

This conversion is specific to the old MRC code and having one set of data vs another set of data, not an example vs a set of data.

This might not be a high priority but it would be needed to verify the pipeline relative to published data.

**Comment by MichaelCurrie** [comment]
The statistics code was also "done" in the sense that I moved the classes and code into the movement_validation repo.  Any lines I couldn't translate completely I left commented out.  So the next steps are all contained in the following module:

i.e. the StatisticsManager and WormStatistics classes are defined here:

https://github.com/openworm/movement_validation/blob/master/movement_validation/statistics/manager.py

That's all you need, AFAIK.  No need to go back to the MatLab code at all.  But agreed, some work remains here to finish so we should leave this issue open.

**Comment by MichaelCurrie** [comment]
I'm working on `manager.py` right now so I'm going to move some of my notes on progress from the preamble of that code file to here:

```
A translation of Matlab code written by Jim Hokanson,
in the SegwormMatlabClasses GitHub repo.  Original code paths:

DONE:
                                                              # of lines
SegwormMatlabClasses / +seg_worm / +stats / +hist / @manager     410
SegwormMatlabClasses / +seg_worm / +stats / event_specs.m        143
SegwormMatlabClasses / +seg_worm / +stats / movement_specs.m      81
SegwormMatlabClasses / +seg_worm / +stats / simple_specs.m        45
SegwormMatlabClasses / +seg_worm / +stats / specs.m               70
SegwormMatlabClasses / +seg_worm / +stats / +hist / docs         (several CSV files)
SegwormMatlabClasses / +seg_worm / +stats / @hist                339

ALMOST COMPLETE:
SegwormMatlabClasses / +seg_worm / @stats                        231 
SegwormMatlabClasses / +seg_worm / +stats / @manager              61



MIGHT NOT BE NEEDED:
SegwormMatlabClasses / +seg_worm / +stats / +helpers / fexact.m  405
SegwormMatlabClasses / +seg_worm / +stats / +helpers / swtest.m  260
SegwormMatlabClasses / +seg_worm / +stats / @hist_specs           50 (unknown how used - @JimHokanson)
SegwormMatlabClasses / +seg_worm / +w / *                         38 files, lots of lines of code... is this necessary?


                                                          TOTAL 2095 lines + several CSV files
                                                               unclear so far if the CSV files
                                                               are being loaded and used by the
                                                               code or if they are just docs
```

**Comment by MichaelCurrie** [comment]
Statistics code is now completely translated and working.  For each histogram we have a value from the Shapiro-Wilk normality test, and for each feature we have a p-value from both a parameterized (Student's t) and non-parameterized (Wilcoxon signed-rank) test.  We also have a "q-value" following Storey et. al (2002) which tried to adjust for the passive p-hacking that could take place when we try to reject hundreds of null hypotheses at once corresponding to the hundreds of features we are comparing the groups of worms by.

Here's an example of some output, which follows what is available in PDFs from the Schafer Lab's *C. elegans* behavioural database:


![](https://cloud.githubusercontent.com/assets/5267078/8539270/bbe2091c-2436-11e5-9026-323d94436325.png)

The original plots from the .PDFs available at the [**C. elegans behavioural database**](http://wormbehavior.mrc-lmb.cam.ac.uk/) look like this:

![image](https://cloud.githubusercontent.com/assets/5267078/8539307/e4de9236-2436-11e5-8fa2-25492f778f6d.png)

![image](https://cloud.githubusercontent.com/assets/5267078/8539309/efde983e-2436-11e5-94e6-84c483c4e013.png)
