### ISSUE TITLE
Port the feature info filtering

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/movement_validation#88]
somewhere I've seen code that is meant to select features from videos that fufill certain requirements - recording date, strain, on or off food, etc.

(Originally described by Jim [in this comment](https://github.com/JimHokanson/SegwormMatlabClasses/issues/10#issuecomment-58836690))

**Comment by JimHokanson** [comment]
This is currently being moved forward by the feature database work that @joebowen has been doing.

**Comment by MichaelCurrie** [comment]
Let's close this issue here then.
